name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploying
      uses: appleboy/ssh-action@master
      with:
        host: 91.227.18.79
        username: tg_binance_notifier_bot
        key: ${{ secrets.SECRET_KEY }}
        port: 22
        script: |
          git -C "/home/tg_binance_notifier_bot/TgBinanceNotifierBot" pull
          cd /home/tg_binance_notifier_bot/TgBinanceNotifierBot
          docker-compose down
          docker-compose rm -fsv
          docker-compose up -d --build

          docker exec binance_bot alembic upgrade head
          docker start binance_bot